# Generated by Django 3.2 on 2021-04-30 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dj_rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
